--------------------------------------------------------
--  File created - Tuesday-December-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "MENU" 
   (	"ID_MENU" VARCHAR2(5 BYTE), 
	"NAMA" VARCHAR2(20 BYTE), 
	"HARGA" NUMBER(8,0), 
	"JENIS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MENU
SET DEFINE OFF;
Insert into MENU (ID_MENU,NAMA,HARGA,JENIS) values ('B001','Es Teh','5000','1');
Insert into MENU (ID_MENU,NAMA,HARGA,JENIS) values ('F001','Ayam Bakar','15000','0');
Insert into MENU (ID_MENU,NAMA,HARGA,JENIS) values ('D001','Pudding','6000','2');
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MENU_PK" ON "MENU" ("ID_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("ID_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MENU" MODIFY ("ID_MENU" NOT NULL ENABLE);
 
  ALTER TABLE "MENU" MODIFY ("NAMA" NOT NULL ENABLE);
 
  ALTER TABLE "MENU" MODIFY ("HARGA" NOT NULL ENABLE);
 
  ALTER TABLE "MENU" MODIFY ("JENIS" NOT NULL ENABLE);
