/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.gui;

import app.db.OracleConnection;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows
 */
public class Pesanan extends javax.swing.JFrame {

    /**
     * Creates new form Pesanan
     */
    public Pesanan() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nota = new javax.swing.JTextArea();
        simpanNota = new javax.swing.JLabel();
        tidakButton = new javax.swing.JButton();
        iyaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesanan");

        nota.setEditable(false);
        nota.setColumns(20);
        nota.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        nota.setRows(5);
        nota.setText(getNota());
        jScrollPane1.setViewportView(nota);

        simpanNota.setText("Simpan nota?");

        tidakButton.setText("Tidak");
        tidakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakButtonActionPerformed(evt);
            }
        });

        iyaButton.setText("Iya");
        iyaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iyaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tidakButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iyaButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanNota))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simpanNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iyaButton)
                    .addComponent(tidakButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iyaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iyaButtonActionPerformed
        FileOutputStream outStream = null;
        
        JFileChooser choose = new JFileChooser();
        this.dispose();
        choose.setCurrentDirectory(new File("C:/Users/Windows/Documents/Nota"));
        choose.showSaveDialog(null);
        File outFile = choose.getSelectedFile();
        try {
            outStream = new FileOutputStream(outFile);
            outStream.write(nota.getText().getBytes());
            outStream.close();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            
        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        
        JOptionPane.showMessageDialog(this, "Terima kasih!");
        
        MenuKasir frame = new MenuKasir();
        frame.setVisible(true);
    }//GEN-LAST:event_iyaButtonActionPerformed

    private void tidakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Terima kasih!");
        
        MenuKasir frame = new MenuKasir();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tidakButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesanan().setVisible(true);
            }
        });
    }
    
    public String getNota(){
        try {
            while(true){
                tunai = Integer.parseInt(JOptionPane.showInputDialog(null, "Tunai:"));
                if (tunai<getTotal()){
                    JOptionPane.showMessageDialog(null, "Uang Anda tidak mencukupi", 
                        "Pesan error", JOptionPane.ERROR_MESSAGE);
                } else {
                    break;
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Nilai yang dimasukkan berupa angka", 
                    "Pesan error", JOptionPane.ERROR_MESSAGE);
        }
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat date = new SimpleDateFormat("EEEE, d MMMM yyyy HH:mm:ss");
        String tanggal = date.format(cal.getTime());
        
        String daftar = "";
        
        OracleConnection ora = new OracleConnection();
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;

        conn = ora.getConnection();
        try {
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM pesan");

            while (rs.next()) {
                String nama = rs.getString(2);
                String qty = Integer.toString(rs.getInt(4));
                String harga = Integer.toString(rs.getInt(3));
                String subtotal = Integer.toString(rs.getInt(5));
                String baris;
                if (nama.length()>8){
                    baris = nama+"\t"+qty+"\t"+harga+"\t"
                        +subtotal+"\n";
                } else {
                    baris = nama+"\t\t"+qty+"\t"+harga+"\t"
                        +subtotal+"\n";
                }
            
                daftar = daftar+baris;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        
        String nota = 
                "\t     RESTORAN 'BERSAMA'\n"
                +"\t     Paingan, Yogyakarta\n"
                +"      "+tanggal+"\n"
                +"==============================================\n"
                +"Nama\t\tQty     Harga   Subtotal\n"
                +"==============================================\n"
                +daftar
                +"==============================================\n"
                +"Total\t\t\t\tRp"+getTotal()+"\n"
                +"Tunai\t\t\t\tRp"+tunai+"\n"
                +"Kembali\t\t\t\tRp"+(tunai-getTotal())+"\n"
                +"==============================================\n"
                +"      Terima kasih atas kunjungan Anda";
        tunai=0;
        return nota;
    }
    
    public int getTotal(){
        int total = 0;
        
        OracleConnection ora = new OracleConnection();
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;

        conn = ora.getConnection();
        try {
            st = conn.createStatement();
            rs = st.executeQuery("SELECT SUM(subtotal) FROM pesan");
            
            while(rs.next()){
                total = rs.getInt(1);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        return total;
    }
    
    private int tunai;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iyaButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea nota;
    private javax.swing.JLabel simpanNota;
    private javax.swing.JButton tidakButton;
    // End of variables declaration//GEN-END:variables
}
